datasets:
  - shp

local_dirs:
  - /home/scratch/virajm
  - /home/scratch/vdas
  - /scr-ssd
  - /scr
  - .cache

model_dir: jeopardy_sft_dropout_2023-09-04_19-49-24_466638/LATEST

seed: 42

# the maximum allowed length for an input (prompt + response)
max_length: 512

# the maximum allowed length for a prompt
max_prompt_length: 256

n_examples: null
batch_size: 64
num_samples: 10
have_llm_dropout: false
dropout: False
llm_dropout: 0.05
lora_dropout: 0.05
epinet: False
lambda_val: 0.05
average_logprob: True

defaults:
- _self_
- model: blank_model_fp32
- loss: sft # which loss function, either sft or dpo (specify loss.beta if using dpo)